CREATE DATABASE coinsmaster;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS  teams (
  code VARCHAR NOT NULL UNIQUE,
  name VARCHAR NOT NULL,
  classroom VARCHAR NOT NULL,
  habilities VARCHAR NOT NULL
);

CREATE TABLE users (
  id UUID NOT NULL UNIQUE DEFAULT uuid_generate_v4(),
  name VARCHAR NOT NULL,
  photo VARCHAR,
  team_code VARCHAR NOT NULL,
  role VARCHAR NOT NULL,
  FOREIGN KEY (team_code) REFERENCES teams (code)
);
